"""Add BankAccount table

Revision ID: 0bb1dde985b2
Revises: 
Create Date: 2025-12-10 11:12:16.966069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb1dde985b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankaccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('account_type', sa.Enum('credit', 'debit', name='accounttype'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bankaccount_account_name'), 'bankaccount', ['account_name'], unique=False)
    op.create_index(op.f('ix_bankaccount_bank_name'), 'bankaccount', ['bank_name'], unique=False)
    op.create_index(op.f('ix_bankaccount_id'), 'bankaccount', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bankaccount_id'), table_name='bankaccount')
    op.drop_index(op.f('ix_bankaccount_bank_name'), table_name='bankaccount')
    op.drop_index(op.f('ix_bankaccount_account_name'), table_name='bankaccount')
    op.drop_table('bankaccount')
    # ### end Alembic commands ###
