"""add_category_table

Revision ID: 0ef3564b4bf8
Revises: eddabb0cef87
Create Date: 2025-12-12 11:06:41.851242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef3564b4bf8'
down_revision: Union[str, Sequence[str], None] = 'eddabb0cef87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    # ### end Alembic commands ###
    
    # Insert default 'others' category
    op.execute(
        """
        INSERT INTO category (name, description)
        VALUES ('others', 'Default category for uncategorized transactions')
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Delete default 'others' category
    op.execute("DELETE FROM category WHERE name = 'others'")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
