"""add_transaction_category_relationship

Revision ID: d22efa84079d
Revises: 0ef3564b4bf8
Create Date: 2025-12-12 11:18:26.512661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22efa84079d'
down_revision: Union[str, Sequence[str], None] = '0ef3564b4bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_category',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('transaction_id', 'category_id')
    )
    # ### end Alembic commands ###
    
    # Assign all existing transactions to 'others' category
    op.execute(
        """
        INSERT INTO transaction_category (transaction_id, category_id)
        SELECT t.id, c.id
        FROM transaction t
        CROSS JOIN category c
        WHERE c.name = 'others'
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_category')
    # ### end Alembic commands ###
