"""Add statement_format table

Revision ID: eddabb0cef87
Revises: e0e7e838d659
Create Date: 2025-12-10 13:56:16.138258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eddabb0cef87'
down_revision: Union[str, Sequence[str], None] = 'e0e7e838d659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statementformat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('format_name', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('data_start_row', sa.Integer(), nullable=False, comment='Row number where transaction data begins (1-indexed)'),
    sa.Column('date_column', sa.String(), nullable=False, comment='Column identifier for transaction date'),
    sa.Column('narration_column', sa.String(), nullable=False, comment='Column identifier for narration/description'),
    sa.Column('withdrawal_column', sa.String(), nullable=False, comment='Column identifier for withdrawal/debit amount'),
    sa.Column('deposit_column', sa.String(), nullable=False, comment='Column identifier for deposit/credit amount'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statementformat_bank_name'), 'statementformat', ['bank_name'], unique=False)
    op.create_index(op.f('ix_statementformat_format_name'), 'statementformat', ['format_name'], unique=False)
    op.create_index(op.f('ix_statementformat_id'), 'statementformat', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statementformat_id'), table_name='statementformat')
    op.drop_index(op.f('ix_statementformat_format_name'), table_name='statementformat')
    op.drop_index(op.f('ix_statementformat_bank_name'), table_name='statementformat')
    op.drop_table('statementformat')
    # ### end Alembic commands ###
